labeling/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('form/<str:model>/<slug:kind>/<int:number>', views.get_form),
    path('specific/<str:model>/<slug:kind>/<int:number>', views.specific, name='specific'),
]

umllabels/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import index, validation, get_form
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('labeling/', include(('labeling.urls', 'labeling'), namespace="labeling")),
    path('admin/', admin.site.urls, name='admin'),
    path('', index),
    path('validation/', validation, name='validation'),
    path('validation/form/<str:model>/<slug:kind>/<int:number>', get_form)
    # path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))
]

labeling/models.py
from django.db import models

# Create your models here.
class Fragment(models.Model):
    kind = models.CharField(max_length=50)
    number = models.IntegerField(blank=True, null=True)
    model = models.ForeignKey('Model', models.DO_NOTHING, db_column='model', blank=True, null=True)       
    unique_id = models.AutoField(primary_key=True, blank=True, null=False, default=0)

    def __str__(self):
        return f"{self.model}_{self.kind}{self.number}"


class Model(models.Model):
    name = models.CharField(primary_key=True, blank=True, null=False, max_length=50)
    classes = models.IntegerField(blank=True, null=True)
    relations = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

class Label(models.Model):
    label = models.TextField()
    fragment = models.ForeignKey('Fragment', models.DO_NOTHING, null=True)
    in_english = models.BooleanField(default=True)

    validated = models.BooleanField(default=False)

    def __str__(self):
        return str(self.fragment)

labeling/forms.py
from labeling.sampler import Sampler
from django import forms

from .models import Label

class LabelForm(forms.Form):
    not_in_english = forms.BooleanField(required=False, label="This fragment/model is not in English.", help_text="\n", initial=False)
    description = forms.CharField(label='Description', max_length=500, widget=forms.Textarea)
    def process(self, fragment):

        # check if already labeled
        try:
            Label.objects.get(fragment=fragment)
        except Label.DoesNotExist:
            pass
        else:
            raise DuplicateLabelException

        Label.objects.create(label=self.cleaned_data["description"], fragment=fragment, in_english=not self.cleaned_data["not_in_english"])
        Sampler.current_class_count = fragment.model.classes

class DuplicateLabelException(Exception):
    pass

umllabels/forms.py
from django import forms

from labeling.models import Label

class ValidationForm(forms.Form):
    isAcceptable = forms.BooleanField(required=False, label="This label is acceptable.", initial=True)

labeling/views.py
import json
from labeling.sampler import Sampler, block
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.http.request import HttpRequest
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect

# Create your views here.
from .models import Label, Fragment, Model

from .forms import DuplicateLabelException, LabelForm

def index(request: HttpRequest, model=None, fragment=None):

    # Cookies
    try:
        last_fragment = request.COOKIES["active_fragment"]
    except KeyError:
        last_fragment = None

    # clear reservations from the last fragment
    if last_fragment is not None:
        previous_fragments = []
        for previous_fragment in json.loads(request.COOKIES["reserved_fragments"]):
            if previous_fragment['filter'] == "animals":
                previous_fragments.append(Fragment.objects.get(model__name=previous_fragment['model'], kind=previous_fragment['kind'], number=previous_fragment['number']))
        threads = Sampler.free_fragments(previous_fragments)
        for sleeper in threads:
            if sleeper is not None:
                sleeper.join(5)

    form = LabelForm()

    if model == None or fragment == None:
        model, fragment = Sampler.next()
    else:
        @block(60)
        def block_this(): return fragment
        block_this()

    # check for end conditions
    if model == None and fragment == None:
        return HttpResponse("Labeling complete!")
    elif model == None and fragment != None:
        return HttpResponseForbidden("No model but there is a fragment!")
    elif model != None and fragment == None:
        return HttpResponseForbidden("No fragment on this model")
    else:
        pass # business as usual

    # more models
    more_models = Sampler.more_models(5, exclude=model)
    more_fragments = Sampler.more_fragments(model=model, limit=5)

    more = []

    for m in more_models:
        incomplete_fragment = Sampler.excluding_reserved(Fragment.objects.filter(model=m, label__isnull=True))
        if len(incomplete_fragment) == 0:
            # block the model when all fragments are blocked
            @block(60)
            def block_this(): return m
            block_this()
            continue
        else:
            incomplete_fragment = incomplete_fragment.first()
        more.append({
            "filter": "nature", # nature for models
            "image": f"fragments/{m.name}.png",
            "caption_header": m.name,
            "caption": f"{m.classes} classes, {m.relations} relations",
            "model": m.name,
            "kind": incomplete_fragment.kind,
            "number": incomplete_fragment.number,
        })

    for f in more_fragments:
        more.append({
            "filter": "animals", # nature for models
            "image": f"fragments/{f}.png",
            "caption_header": f"Fragment",
            "caption": f"{f.kind} {f.number}",
            "model": model.name,
            "kind": f.kind,
            "number": f.number,
        })

    context = {
        "shown_model": f"fragments/{model.name}.png",
        "shown_model_name": model.name,
        "shown_fragment": f"fragments/{model.name}_{fragment.kind}{fragment.number}.png",
        "fragment_kind": fragment.kind,
        "fragment_number": fragment.number,
        "form": form,
        "more": more,
    }
    response = render(request, "labeling/index.html", context=context)

    # Cookies
    # Log on this response
    response.set_cookie("reserved_fragments", json.dumps(more), max_age=60)
    response.set_cookie("active_fragment", context["shown_fragment"], max_age=60)

    return response

def get_form(request, model, kind, number):
    
    # form
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LabelForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            fragment = Fragment.objects.get(
                model=Model.objects.get(name=model),
                number=number,
                kind=kind
            )
            try:
                form.process(fragment)
            except DuplicateLabelException:
                return HttpResponse(f"An existing label already exists for {fragment}. Back to <a href='/'>Menu</a>.")

            return HttpResponseRedirect('/labeling/')
        else:
            return HttpResponseBadRequest("Invalid form. Back to <a href='/'>Menu</a>.")

    # if a GET (or any other method) we throw an error
    else:
        return HttpResponseForbidden(content="You cannot come here")

def specific(request, model, kind, number):
    model = Model.objects.get(name=model)
    fragment = Fragment.objects.get(model=model, kind=kind, number=number)
    return index(request, model=model, fragment=fragment)

umllabels/views.py
from umllabels.forms import ValidationForm
from django.shortcuts import redirect, render
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden

from labeling.models import Fragment, Label, Model

# Home index

def index(request):
    context = {
        "total_models": Model.objects.all().filter(classes__gt=0).count(),
        "total_fragments": Fragment.objects.count(),
        "models_done": Model.objects.filter(
            fragment__label__isnull=False
        ).distinct().count(),
        "fragments_done": Label.objects.count()
    }
    return render(request, "umllabels/index.html", context=context)

def validation(request):

    # get a label
    label : Label = Label.objects.filter(validated=False).first()

    if label == None:
        # No more labels to validate
        return HttpResponse(f"All received labels are validated. Back to <a href='/'>Menu</a>.")

    fragment : Fragment = label.fragment
    model : Model = fragment.model

    context = {
        "label": label.label,
        "shown_model_name":  model.name,
        "fragment_kind": fragment.kind,
        "fragment_number": fragment.number,
        "form": ValidationForm(),
        "shown_fragment": f"fragments/{fragment}.png",
        "shown_model": f"fragments/{model}.png",
    }
    return render(request, "umllabels/validation.html", context=context)

def get_form(request, model, kind, number):

    # form
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ValidationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            fragment = Fragment.objects.get(
                model=Model.objects.get(name=model),
                number=number,
                kind=kind
            )
            label : Label = Label.objects.get(fragment=fragment)

            # process the data in form.cleaned_data as required
            if form.cleaned_data["isAcceptable"]:
                label.validated = True
                label.save()

            else:
                # delete the label
                label.delete()

            return redirect('/validation/')

    # if a GET (or any other method) we throw an error
    else:
        return HttpResponseForbidden(content="You cannot come here")

labeling/templates/umllabels/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <title>The UML Labeling Initiative</title>
    <!-- 

Get Ready Template

https://templatemo.com/tm-521-get-ready

-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="team" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% load static%}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

    <link rel="stylesheet" href="{% static 'templatemo_521_get_ready/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'templatemo_521_get_ready/css/vegas.min.css' %}">
    <link rel="stylesheet" href="{% static 'templatemo_521_get_ready/css/font-awesome.min.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'templatemo_521_get_ready/css/templatemo-style.css' %}">

    <!-- OVERRIDE CSS -->
    <link rel="stylesheet" href="{% static 'umllabels/home.css' %}">
</head>

<body>

    <!-- PRE LOADER -->
    <section class="preloader">
        <div class="spinner">

            <span class="spinner-rotate"></span>

        </div>
    </section>


    <!-- GRID LINE -->
    <section class="grid">
        <div class="container">
            <div class="row">

                <div class="col-md-2 col-sm-2">
                    <div class="grid-line"></div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <div class="grid-line"></div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <div class="grid-line"></div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <div class="grid-line"></div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <div class="grid-line"></div>
                </div>

            </div>
        </div>
    </section>


    <div class="menu-bg"></div>
    <div class="menu-burger">☰</div>

    <div class="menu-items">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-2 col-md-4 col-sm-6">
                    <h1>About</h1>
                    <h3>
                        The UML Labeling Initiative is a data labeling project to create a large data set of UML class
                        diagrams with their English description.
                    </h3>
                </div>

                <div class="col-md-4 col-sm-6">
                    <address>
                        <h1>Contact</h1>
                        <h3><a href="mailto: song.yang.1@umontreal.ca">song.yang.1@umontreal.ca</a>
                        </h3>
                    </address>
                </div>
            </div>
        </div>
    </div>


    <!-- HOME -->
    <section id="home">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">

                <div class="col-md-12 col-sm-12">
                    <div class="home-info">
                        <h1>The UML Labeling Initiative</h1>
                        <!-- NOT USED You can change the date time in init.js file -->
                        <ul class="countdown">
                            <li>
                                <span class="models">{{ total_models }}</span>
                                <h3>Models</h3>
                            </li>
                            <li>
                                <span class="fragments">{{ total_fragments }}</span>
                                <h3>Fragments</h3>
                            </li>
                            <li>
                                <span class="models_labeled">{{ models_done }}</span>
                                <h3>Labeled Models</h3>
                            </li>
                            <li>
                                <span class="fragments_labeled">{{ fragments_done }}</span>
                                <h3>Labeled Fragments</h3>
                            </li>
                        </ul>

                        <button class="button" style="vertical-align:middle" onclick="location.href={% url 'labeling:index' %}"><span>Start </span></button>
                        <button class="button" style="vertical-align:middle" onclick="location.href={% url 'validation' %}"><span>Validate </span></button>
                        <button class="button" style="vertical-align:middle" onclick="location.href={% url 'admin:index' %}"><span>Admin </span></button>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <!-- SCRIPTS -->
    <script>
        var image1 = "{% static 'templatemo_521_get_ready/images/slide-image01.jpg' %}";
        var image2 = "{% static 'templatemo_521_get_ready/images/slide-image02.jpg' %}";
    </script>

    <script src="{% static 'templatemo_521_get_ready/js/jquery.js' %}"></script>
    <script src="{% static 'templatemo_521_get_ready/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'templatemo_521_get_ready/js/vegas.min.js' %}"></script>
    <!-- <script src="{% static 'templatemo_521_get_ready/js/countdown.js' %}"></script> -->
    <!-- <script src="{% static 'templatemo_521_get_ready/js/init.js' %}"></script> -->
    <script src="{% static 'templatemo_521_get_ready/js/custom.js' %}"></script>

</body>

</html>

labeling/templates/umllabels/validation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />

    {% load static%}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

    <link href="{% static 'templatemo_544_comparto/fontawesome/css/all.min.css' %}" rel="stylesheet" />
    <link href="{% static 'templatemo_544_comparto/css/templatemo-comparto.css' %}" rel="stylesheet" />

    {% comment %} Override {% endcomment %}
    <link href="{% static 'umllabels/labeling.css' %}" rel="stylesheet" />
    <title>Labeling | The UML Labeling Initiative</title>
    <!--

Comparto TemplateMo

https://templatemo.com/tm-544-comparto

-->
</head>

<body>
    <!-- Back to top button -->
    <a id="button"><i class="fas fa-angle-up fa-2x"></i></a>
    <div class="container-fluid">
        <div class="tm-site-header tm-mb-1">
            <div class="tm-site-name-container tm-bg-color-1" style="padding-top: 19px;padding-bottom: 19px;">
                <a href="/"><h1 class="tm-text-white">Validation</h1></a>
            </div>
        </div>
        <section class="tm-mb-1 tm-row tm-services-row" id="services">
            <div class="tm-section-2-l">
                <article class="tm-bg-color-6 tm-box-pad tm-mb-1">
                    <h2 class="tm-mb-2">1 Sample to validate </h2>
                    <div class="image-container" id="tutorial-model">
                        <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                        <img class="drag-image" src="{% static shown_fragment %}" alt="Shown fragment" />
                    </div>
                </article>
                <div class="tm-bg-color-7 tm-em-box">
                {{ label | linebreaks }}
                    <form action="/validation/form/{{ shown_model_name }}/{{ fragment_kind }}/{{ fragment_number }}" method="post">
                            {% csrf_token %}
                            {{ form }}
                        <div class="in-rows">
                            <input type="submit" class="tm-btn tm-btn-2" value="Submit" id="form-submit">
                        </div>
                    </form>
                </div>
            </div>
            <div class="tm-section-2-r">
                Your given model is <b>{{shown_model_name}}</b>. Pan images with mouse and zoom by scrolling.
                <br>
                Someone has provided a description for the fragment. Is it an acceptable label? If rejected,
                the label will be sent back to the labeling pool.
                <div class="image-container" id="tutorial-model">
                    <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                    <img class="drag-image" src="{% static shown_model %}" alt="Shown model" />
                </div>
                <button type="button" class="re-center-button ml-auto tm-btn tm-btn-3">Center</button>
            </div>
        </section>
    </div> <!-- .container -->

    <script src="{% static 'templatemo_544_comparto/js/jquery.min.js' %}"></script>
    <!-- https://jquery.com/download/ -->
    <script src="{% static 'templatemo_544_comparto/js/imagesloaded.pkgd.min.js' %}"></script>
    <!-- https://imagesloaded.desandro.com/ -->
    <script src="{% static 'templatemo_544_comparto/js/isotope.pkgd.min.js' %}"></script>
    <!-- https://isotope.metafizzy.co/ -->
    <script src="{% static 'templatemo_544_comparto/js/jquery.singlePageNav.min.js' %}"></script>
    <!-- https://github.com/ChrisWojcik/single-page-nav -->
    <script src="{% static 'umllabels/drag.js' %}"></script>
    <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div-->
    <script>

        // Scroll to Top button
        var btn = $('#button');

        $(window).scroll(function () {
            if ($(window).scrollTop() > 300) {
                btn.addClass('show');
            } else {
                btn.removeClass('show');
            }
        });

        btn.on('click', function (e) {
            e.preventDefault();
            $('html, body').animate({ scrollTop: 0 }, '300');
        });

        // DOM is ready
        $(function () {
            // Single Page Nav
            $('#tm-nav').singlePageNav({ speed: 600 });

            // Smooth Scroll (https://css-tricks.com/snippets/jquery/smooth-scrolling/)
            $('a[href*="#"]')
                // Remove links that don't actually link to anything
                .not('[href="#"]')
                .not('[href="#0"]')
                .click(function (event) {
                    // On-page links
                    if (
                        location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '')
                        &&
                        location.hostname == this.hostname
                    ) {
                        // Figure out element to scroll to
                        var target = $(this.hash);
                        target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                        // Does a scroll target exist?
                        if (target.length) {
                            // Only prevent default if animation is actually gonna happen
                            event.preventDefault();
                            $('html, body').animate({
                                scrollTop: target.offset().top
                            }, 600, function () {
                                // Callback after animation
                                // Must change focus!
                                var $target = $(target);
                                $target.focus();
                                if ($target.is(":focus")) { // Checking if the target was focused
                                    return false;
                                } else {
                                    $target.attr('tabindex', '-1'); // Adding tabindex for elements not focusable
                                    $target.focus(); // Set focus again
                                };
                            });
                        }
                    }
                });

            /* Isotope Gallery */

            // init isotope
            var $gallery = $(".tm-gallery").isotope({
                itemSelector: ".tm-gallery-item",
                layoutMode: "fitRows"
            });
            // layout Isotope after each image loads
            $gallery.imagesLoaded().progress(function () {
                $gallery.isotope("layout");
            });

            $(".filters-button-group").on("click", "a", function () {
                var filterValue = $(this).attr("data-filter");
                $gallery.isotope({ filter: filterValue });
            });

            $(".tabgroup > div").hide();
            $(".tabgroup > div:first-of-type").show();
            $(".tabs a").click(function (e) {
                e.preventDefault();
                var $this = $(this),
                    tabgroup = "#" + $this.parents(".tabs").data("tabgroup"),
                    others = $this
                        .closest("li")
                        .siblings()
                        .children("a"),
                    target = $this.attr("href");
                others.removeClass("active");
                $this.addClass("active");
            });
        });
        
    </script>
</body>

</html>