labeling/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('form/<str:model>/<slug:kind>/<int:number>', views.get_form),
    path('specific/<str:model>/<slug:kind>/<int:number>', views.specific, name='specific'),
]

umllabels/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import index, validation, get_form
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('labeling/', include(('labeling.urls', 'labeling'), namespace="labeling")),
    path('admin/', admin.site.urls, name='admin'),
    path('', index),
    path('validation/', validation, name='validation'),
    path('validation/form/<str:model>/<slug:kind>/<int:number>', get_form)
    # path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')))
]

labeling/models.py
from django.db import models

# Create your models here.
class Fragment(models.Model):
    kind = models.CharField(max_length=50)
    number = models.IntegerField(blank=True, null=True)
    model = models.ForeignKey('Model', models.DO_NOTHING, db_column='model', blank=True, null=True)       
    unique_id = models.AutoField(primary_key=True, blank=True, null=False, default=0)

    def __str__(self):
        return f"{self.model}_{self.kind}{self.number}"


class Model(models.Model):
    name = models.CharField(primary_key=True, blank=True, null=False, max_length=50)
    classes = models.IntegerField(blank=True, null=True)
    relations = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

class Label(models.Model):
    label = models.TextField()
    fragment = models.ForeignKey('Fragment', models.DO_NOTHING, null=True)
    in_english = models.BooleanField(default=True)

    validated = models.BooleanField(default=False)

    def __str__(self):
        return str(self.fragment)

labeling/forms.py
from labeling.sampler import Sampler
from django import forms

from .models import Label

class LabelForm(forms.Form):
    not_in_english = forms.BooleanField(required=False, label="This fragment/model is not in English.", help_text="\n", initial=False)
    description = forms.CharField(label='Description', max_length=500, widget=forms.Textarea)
    def process(self, fragment):

        # check if already labeled
        try:
            Label.objects.get(fragment=fragment)
        except Label.DoesNotExist:
            pass
        else:
            raise DuplicateLabelException

        Label.objects.create(label=self.cleaned_data["description"], fragment=fragment, in_english=not self.cleaned_data["not_in_english"])
        Sampler.current_class_count = fragment.model.classes

class DuplicateLabelException(Exception):
    pass

labeling/views.py
import json
from labeling.sampler import Sampler, block
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.http.request import HttpRequest
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect

# Create your views here.
from .models import Label, Fragment, Model

from .forms import DuplicateLabelException, LabelForm

def index(request: HttpRequest, model=None, fragment=None):

    # Cookies
    try:
        last_fragment = request.COOKIES["active_fragment"]
    except KeyError:
        last_fragment = None

    # clear reservations from the last fragment
    if last_fragment is not None:
        previous_fragments = []
        for previous_fragment in json.loads(request.COOKIES["reserved_fragments"]):
            if previous_fragment['filter'] == "animals":
                previous_fragments.append(Fragment.objects.get(model__name=previous_fragment['model'], kind=previous_fragment['kind'], number=previous_fragment['number']))
        threads = Sampler.free_fragments(previous_fragments)
        for sleeper in threads:
            if sleeper is not None:
                sleeper.join(5)

    form = LabelForm()

    if model == None or fragment == None:
        model, fragment = Sampler.next()
    else:
        @block(60)
        def block_this(): return fragment
        block_this()

    # check for end conditions
    if model == None and fragment == None:
        return HttpResponse("Labeling complete!")
    elif model == None and fragment != None:
        return HttpResponseForbidden("No model but there is a fragment!")
    elif model != None and fragment == None:
        return HttpResponseForbidden("No fragment on this model")
    else:
        pass # business as usual

    # more models
    more_models = Sampler.more_models(5, exclude=model)
    more_fragments = Sampler.more_fragments(model=model, limit=5)

    more = []

    for m in more_models:
        incomplete_fragment = Sampler.excluding_reserved(Fragment.objects.filter(model=m, label__isnull=True))
        if len(incomplete_fragment) == 0:
            # block the model when all fragments are blocked
            @block(60)
            def block_this(): return m
            block_this()
            continue
        else:
            incomplete_fragment = incomplete_fragment.first()
        more.append({
            "filter": "nature", # nature for models
            "image": f"fragments/{m.name}.png",
            "caption_header": m.name,
            "caption": f"{m.classes} classes, {m.relations} relations",
            "model": m.name,
            "kind": incomplete_fragment.kind,
            "number": incomplete_fragment.number,
        })

    for f in more_fragments:
        more.append({
            "filter": "animals", # nature for models
            "image": f"fragments/{f}.png",
            "caption_header": f"Fragment",
            "caption": f"{f.kind} {f.number}",
            "model": model.name,
            "kind": f.kind,
            "number": f.number,
        })

    context = {
        "shown_model": f"fragments/{model.name}.png",
        "shown_model_name": model.name,
        "shown_fragment": f"fragments/{model.name}_{fragment.kind}{fragment.number}.png",
        "fragment_kind": fragment.kind,
        "fragment_number": fragment.number,
        "form": form,
        "more": more,
    }
    response = render(request, "labeling/index.html", context=context)

    # Cookies
    # Log on this response
    response.set_cookie("reserved_fragments", json.dumps(more), max_age=60)
    response.set_cookie("active_fragment", context["shown_fragment"], max_age=60)

    return response

def get_form(request, model, kind, number):
    
    # form
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LabelForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            fragment = Fragment.objects.get(
                model=Model.objects.get(name=model),
                number=number,
                kind=kind
            )
            try:
                form.process(fragment)
            except DuplicateLabelException:
                return HttpResponse(f"An existing label already exists for {fragment}. Back to <a href='/'>Menu</a>.")

            return HttpResponseRedirect('/labeling/')
        else:
            return HttpResponseBadRequest("Invalid form. Back to <a href='/'>Menu</a>.")

    # if a GET (or any other method) we throw an error
    else:
        return HttpResponseForbidden(content="You cannot come here")

def specific(request, model, kind, number):
    model = Model.objects.get(name=model)
    fragment = Fragment.objects.get(model=model, kind=kind, number=number)
    return index(request, model=model, fragment=fragment)

labeling/templates/labeling/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />

    {% load static%}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

    <link href="{% static 'templatemo_544_comparto/fontawesome/css/all.min.css' %}" rel="stylesheet" />
    <link href="{% static 'templatemo_544_comparto/css/templatemo-comparto.css' %}" rel="stylesheet" />

    {% comment %} Override {% endcomment %}
    <link href="{% static 'umllabels/labeling.css' %}" rel="stylesheet" />
    <title>Labeling | The UML Labeling Initiative</title>
    <!--

Comparto TemplateMo

https://templatemo.com/tm-544-comparto

-->
</head>

<body>
    <!-- Back to top button -->
    <a id="button"><i class="fas fa-angle-up fa-2x"></i></a>
    <div class="container-fluid">
        <div class="tm-site-header tm-mb-1">
            <div class="tm-site-name-container tm-bg-color-1" style="padding-top: 19px;padding-bottom: 19px;">
                <a href="/"><h1 class="tm-text-white">Labeling</h1></a>
            </div>
            <div class="tm-nav-container tm-bg-color-8">
                <nav class="tm-nav" id="tm-nav">
                    <ul>
                        <li class="tm-nav-item">
                            <a href="#services" class="tm-nav-link">
                                <span class="tm-mb-1">1 Sample</span>
                            </a>
                        </li>
                        <li class="tm-nav-item">
                            <a href="#gallery" class="tm-nav-link">
                                <span class="tm-mb-1">2 More</span>
                            </a>
                        </li>
                        <li class="tm-nav-item">
                            <a href="#contact" class="tm-nav-link" id="tutorial-nav">
                                <span class="tm-nav-text tm-mb-1">3 Tutorial</span>                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <section class="tm-mb-1 tm-row tm-services-row" id="services">
            <div class="tm-section-2-l">
                <article class="tm-bg-color-6 tm-box-pad tm-mb-1">
                    <h2 class="tm-mb-2">1 Sample to label </h2>
                    <a class="tm-btn tm-btn-2" href="#gallery">Change Sample</a>
                    <div class="image-container" id="tutorial-model">
                        <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                        <img class="drag-image" src="{% static shown_fragment %}" alt="Shown fragment" />
                    </div>
                </article>

                <div class="tm-bg-color-7 tm-em-box">
                    <form action="/labeling/form/{{ shown_model_name }}/{{ fragment_kind }}/{{ fragment_number }}" method="post">
                            {% csrf_token %}
                            {{ form }}
                        <div class="in-rows">
                            <input type="submit" class="tm-btn tm-btn-2" value="Submit" id="form-submit">
                        </div>
                    </form>
                </div>
            </div>
            <div class="tm-section-2-r">
                Your given model is <b>{{shown_model_name}}</b>. Pan images with mouse and zoom by scrolling.
                <br>
                Describe what the fragment on the left means in English. The larger model is only given for context.
                Don't describe the entire model. <a href="#contact">(See Tutorial)</a>
                <div class="image-container" id="tutorial-model">
                    <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                    <img class="drag-image" src="{% static shown_model %}" alt="Shown model" />
                </div>
                <button type="button" class="re-center-button ml-auto tm-btn tm-btn-3">Center</button>
            </div>
        </section>
        <section class="tm-bg-color-4 tm-mb-3 tm-gallery-section" id="gallery">
            <div class="tm-gallery-header">
                <h2 class="tm-mb-1 text-right">2 More data samples</h2>
                <ul class="tm-gallery-filter tabs clearfix filters-button-group">
                    <li><a role="button" href="#" class="active" data-filter="*">Show All</a></li>
                    . <li><a role="button" href="#" data-filter=".nature">Models</a></li>
                    . <li><a role="button" href="#" data-filter=".animals">Fragments</a></li>
                </ul>
            </div>
            <div class="tm-gallery-outer">
                <div class="tm-gallery" id="tm-gallery">
                {% for sample in more %}
                    <div class="tm-gallery-item {{ sample.filter }}">
                        <figure class="effect-bubba">
                            <img src="{% static sample.image %}" alt="Gallery item" class="tm-img-responsive" />
                            <figcaption>
                                <h2> {{sample.caption_header}} </h2>
                                <p> {{sample.caption}} </p>
                                <a href="{% url 'labeling:specific' model=sample.model kind=sample.kind number=sample.number %}">View more</a>
                            </figcaption>
                        </figure>
                    </div>
                {% endfor %}
                </div>
            </div>
        </section> <!-- Gallery -->
        <section id="contact" class="tm-bg-color-5 tm-mb-3">
            <h2 class="tm-text-white tm-contact-title">3 Tutorial example</h2>
            <div class="tm-bg-color-white tm-contact-main">
                <div class="map-outer">
                    Pan the image using the mouse. Scroll to zoom.
                    <div class="image-container" id="tutorial-model">
                        <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                        <img class="drag-image" src="{% static 'umllabels/tutorial/CFG.png' %}" alt="Example model" />
                    </div>
                    <button type="button" class="re-center-button ml-auto tm-btn tm-btn-3">Center</button>
                </div>
                <div class="map-outer">
                    This is a fragment of the larger model.
                    <div class="image-container" id="tutorial-fragment">
                        <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div -->
                        <img class="drag-image" src="{% static 'umllabels/tutorial/CFG_rel2.png' %}"
                            alt="Example model" />
                    </div>
                    <p><i>Description 1:</i> A conditional node has one node that serves as a true condition node.</p>
                    <p><i>Description 2:</i> The conditional node of a CFG has one true condition node. Each such node has
                        one conditional node.</p>
                </div>
                <div class="contact-info-outer">
                    <div class="tm-bg-color-6 contact-info">
                        <p>A fragment is either one class or one relationship between two classes.</p>
                        <p>Describe in English what the fragment is in the context of the model. There may be noise in the data. <a
                                href="https://www.google.com/search?hl=en&q=uml"><u>Don't know UML?</u></a></p>
                        <p>In some cases, the data is not entirely in English. You still have to describe it in English to the best of your knowledge and check the "not in English" box.
                        Optionally, you can change the sample to something else and someone else can try to label that data.</p>
                    </div>
                </div>
            </div>
        </section>
        <footer class="text-center tm-mb-1">
            <p>Copyright &copy; 2021 Song Yang <a href="mailto: song.yang.1@umontreal.ca">song.yang.1@umontreal.ca</a>

                - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
        </footer>
    </div> <!-- .container -->

    <script src="{% static 'templatemo_544_comparto/js/jquery.min.js' %}"></script>
    <!-- https://jquery.com/download/ -->
    <script src="{% static 'templatemo_544_comparto/js/imagesloaded.pkgd.min.js' %}"></script>
    <!-- https://imagesloaded.desandro.com/ -->
    <script src="{% static 'templatemo_544_comparto/js/isotope.pkgd.min.js' %}"></script>
    <!-- https://isotope.metafizzy.co/ -->
    <script src="{% static 'templatemo_544_comparto/js/jquery.singlePageNav.min.js' %}"></script>
    <!-- https://github.com/ChrisWojcik/single-page-nav -->
    <script src="{% static 'umllabels/drag.js' %}"></script>
    <!-- https://usefulangle.com/post/1/jquery-dragging-image-within-div-->
    <script>

        // Scroll to Top button
        var btn = $('#button');

        $(window).scroll(function () {
            if ($(window).scrollTop() > 300) {
                btn.addClass('show');
            } else {
                btn.removeClass('show');
            }
        });

        btn.on('click', function (e) {
            e.preventDefault();
            $('html, body').animate({ scrollTop: 0 }, '300');
        });

        // DOM is ready
        $(function () {
            // Single Page Nav
            $('#tm-nav').singlePageNav({ speed: 600 });

            // Smooth Scroll (https://css-tricks.com/snippets/jquery/smooth-scrolling/)
            $('a[href*="#"]')
                // Remove links that don't actually link to anything
                .not('[href="#"]')
                .not('[href="#0"]')
                .click(function (event) {
                    // On-page links
                    if (
                        location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '')
                        &&
                        location.hostname == this.hostname
                    ) {
                        // Figure out element to scroll to
                        var target = $(this.hash);
                        target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                        // Does a scroll target exist?
                        if (target.length) {
                            // Only prevent default if animation is actually gonna happen
                            event.preventDefault();
                            $('html, body').animate({
                                scrollTop: target.offset().top
                            }, 600, function () {
                                // Callback after animation
                                // Must change focus!
                                var $target = $(target);
                                $target.focus();
                                if ($target.is(":focus")) { // Checking if the target was focused
                                    return false;
                                } else {
                                    $target.attr('tabindex', '-1'); // Adding tabindex for elements not focusable
                                    $target.focus(); // Set focus again
                                };
                            });
                        }
                    }
                });

            /* Isotope Gallery */

            // init isotope
            var $gallery = $(".tm-gallery").isotope({
                itemSelector: ".tm-gallery-item",
                layoutMode: "fitRows"
            });
            // layout Isotope after each image loads
            $gallery.imagesLoaded().progress(function () {
                $gallery.isotope("layout");
            });

            $(".filters-button-group").on("click", "a", function () {
                var filterValue = $(this).attr("data-filter");
                $gallery.isotope({ filter: filterValue });
            });

            $(".tabgroup > div").hide();
            $(".tabgroup > div:first-of-type").show();
            $(".tabs a").click(function (e) {
                e.preventDefault();
                var $this = $(this),
                    tabgroup = "#" + $this.parents(".tabs").data("tabgroup"),
                    others = $this
                        .closest("li")
                        .siblings()
                        .children("a"),
                    target = $this.attr("href");
                others.removeClass("active");
                $this.addClass("active");
            });
        });
        
    </script>
</body>

</html>